name: Update phosphor icons

on:
  schedule:
    - cron: "0 0 * * 1"

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"

      - name: Enable pnpm
        run: corepack enable

      - name: Install
        run: pnpm install

      - name: Update @phosphor-icons/core and regenerate artifacts
        run: pnpm update-phosphor

      - name: Publish updated packages
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
        run: pnpm publish --no-git-checks

