import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import svgtofont from "svgtofont";

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");

const CORE_ASSETS_DIR = path.join(
  repoRoot,
  "node_modules",
  "@phosphor-icons",
  "core",
  "assets",
);

const OUT_DIR = path.join(repoRoot, "packages", "phosphor-core");
const FONTS_DIR = path.join(OUT_DIR, "fonts");

const START_UNICODE = 0xe900; // 59648

type Weight = "thin" | "light" | "regular" | "bold" | "fill" | "duotone";

const WEIGHTS: Weight[] = ["thin", "light", "regular", "bold", "fill", "duotone"];

const FONT_NAME_BY_WEIGHT: Record<Weight, string> = {
  thin: "Phosphor-Thin",
  light: "Phosphor-Light",
  regular: "Phosphor-Regular",
  bold: "Phosphor-Bold",
  fill: "Phosphor-Fill",
  duotone: "Phosphor-Duotone",
};

const SUFFIX_BY_WEIGHT: Record<Weight, string> = {
  thin: "-thin",
  light: "-light",
  regular: "",
  bold: "-bold",
  fill: "-fill",
  duotone: "-duotone",
};

const EXCLUDE_FORMAT: Array<"eot" | "woff" | "woff2" | "svg" | "ttf" | "symbol.svg"> = [
  "eot",
  "woff",
  "woff2",
  "svg",
  "symbol.svg"
];

function stripWeightSuffix(glyphName: string, weight: Weight): string {
  const suffix = SUFFIX_BY_WEIGHT[weight];
  if (!suffix) return glyphName;
  return glyphName.endsWith(suffix) ? glyphName.slice(0, -suffix.length) : glyphName;
}

function parseCodepointFromUnicode(unicodeEntity: string): number | undefined {
  // svgtofont format: "&#59905;"
  const match = unicodeEntity.match(/&#(\d+);/);
  if (!match) return undefined;
  return Number(match[1]);
}

async function listRegularIconNames(): Promise<string[]> {
  const regularDir = path.join(CORE_ASSETS_DIR, "regular");
  const entries = await fs.readdir(regularDir, { withFileTypes: true });
  return entries
    .filter((e) => e.isFile() && e.name.endsWith(".svg"))
    .map((e) => e.name.slice(0, -".svg".length))
    .sort((a, b) => a.localeCompare(b));
}

async function ensureOutDirs() {
  await fs.mkdir(FONTS_DIR, { recursive: true });
}

async function generateGlyphMapFromRegular(): Promise<Record<string, number>> {
  const regularDir = path.join(CORE_ASSETS_DIR, "regular");

  const infoData = await svgtofont({
    src: regularDir,
    dist: FONTS_DIR,
    fontName: FONT_NAME_BY_WEIGHT.regular,
    css: false,
    log: false,
    startUnicode: START_UNICODE,
    excludeFormat: EXCLUDE_FORMAT,
    generateInfoData: true,
  });

  const glyphMap: Record<string, number> = {};

  for (const [name, info] of Object.entries(infoData as Record<string, any>)) {
    const cp = parseCodepointFromUnicode(info?.unicode);
    if (typeof cp === "number") glyphMap[name] = cp;
  }

  if (Object.keys(glyphMap).length === 0) {
    throw new Error("Failed to generate glyphMap from regular svgs.");
  }

  return glyphMap;
}

async function generateFontsForOtherWeights(glyphMap: Record<string, number>) {
  const otherWeights = WEIGHTS.filter((w) => w !== "regular");

  for (const weight of otherWeights) {
    const weightDir = path.join(CORE_ASSETS_DIR, weight);

    await svgtofont({
      src: weightDir,
      dist: FONTS_DIR,
      fontName: FONT_NAME_BY_WEIGHT[weight],
      css: false,
      log: false,
      startUnicode: START_UNICODE,
      excludeFormat: EXCLUDE_FORMAT,
      generateInfoData: false,
      // Force stable codepoints based on glyphMap derived from regular run.
      getIconUnicode: (glyphName: string) => {
        const baseName = stripWeightSuffix(glyphName, weight);
        const cp = glyphMap[baseName];
        const unicodeChar = typeof cp === "number" ? String.fromCodePoint(cp) : "";
        // Returning 0 prevents svgtofont from moving `startUnicode` based on matches.
        return [unicodeChar, 0];
      },
    });
  }
}

function generateIconNameUnion(iconNames: string[]): string {
  const lines: string[] = [];
  lines.push(`// Generated by scripts/generate-icons.ts`);
  lines.push(`export type IconName =`);

  // Keep line lengths reasonable; TS handles unions this size fine in practice.
  const maxPerLine = 1;
  for (const name of iconNames.sort((a, b) => a.localeCompare(b))) {
    lines.push(`  | "${name}"${maxPerLine ? "" : ""}`);
  }

  // Remove leading "| " if icon list is empty.
  if (iconNames.length === 0) {
    return `// Generated by scripts/generate-icons.ts\nexport type IconName = never;\n`;
  }

  return lines.join("\n").replace(/^\s+\|\s/gm, "  | ");
}

async function writeArtifacts(glyphMap: Record<string, number>) {
  const iconNames = Object.keys(glyphMap);

  const glyphMapJson = JSON.stringify(
    iconMapStableOrder(glyphMap),
    null,
    2,
  );

  await fs.writeFile(path.join(OUT_DIR, "glyphMap.json"), glyphMapJson, "utf-8");

  const iconNameUnion = generateIconNameUnion(iconNames);
  await fs.writeFile(path.join(OUT_DIR, "IconName.ts"), iconNameUnion, "utf-8");
}

function iconMapStableOrder(glyphMap: Record<string, number>): Record<string, number> {
  const sorted = Object.keys(glyphMap).sort((a, b) => a.localeCompare(b));
  const out: Record<string, number> = {};
  for (const k of sorted) out[k] = glyphMap[k];
  return out;
}

async function main() {
  await ensureOutDirs();

  // Sanity: `@phosphor-icons/core` should always include regular SVGs.
  await listRegularIconNames();

  const glyphMap = await generateGlyphMapFromRegular();
  await generateFontsForOtherWeights(glyphMap);
  await writeArtifacts(glyphMap);
}

main().catch((err) => {
  console.error(err);
  process.exitCode = 1;
});

